### ISSUE TITLE
My bnetlauncher wont start game

### ISSUE THREAD

**Issue by robinhugy** [dafzor/bnetlauncher#12]
hello!
added the bnetlauncher.exe as non steam game with ow parameter but is wont work
my game not in the default folder but i have a symlink: f:\Games\Battle.net\games\Overwatch\ to h:\Battle.net\games\Overwatch\
battle.net see the game and i can start from it without steam
i see only this in battle.net:
This folder doesn't contain the correct version of this game. Please check the installation path and try again.
Error Code: BLZBNTAGT00000AF0

and its my log file:
[2017-10-07 23:02:50.2046]: Battle.net Launcher for Steam version 1.18.6465.31319 started
[2017-10-07 23:02:50.2096]: Environment: Microsoft Windows NT 6.1.7601 Service Pack 1 (4.0.30319.42000), 64bit
[2017-10-07 23:02:50.2106]: Getting Machine details:
[2017-10-07 23:02:50.2566]: OS: Microsoft Windows 7 Ultimate  (6.1.7601, 64-bit, 1038)
[2017-10-07 23:02:50.2566]: CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz; RAM: 32768MB
[2017-10-07 23:02:50.2576]: GPU: NVIDIA GeForce GTX 660 (2048MB, 22.21.13.8541)
[2017-10-07 23:02:50.2576]: HDD: Samsung SSD 850 PRO 256GB ATA Device, WDC WD1002FAEX-00Y9A0 ATA Device, WDC WD1502FAEX-007BA0 ATA Device, WDC WD1502FAEX-007BA0 ATA Device, WDC WD30EFRX-68EUZN0 ATA Device, WDC WD4003FZEX-00Z4SA0 ATA Device
[2017-10-07 23:02:50.2606]: Exception while trying to retrieve battle.net client path:
[2017-10-07 23:02:50.2626]: System.NullReferenceException: Object reference not set to an instance of an object.
   at bnetlauncher.Program.GetBnetClientPath()
[2017-10-07 23:02:51.3316]: Exception while trying to retrieve battle.net client path:
[2017-10-07 23:02:51.3326]: System.NullReferenceException: Object reference not set to an instance of an object.
   at bnetlauncher.Program.GetBnetClientPath()
[2017-10-07 23:02:51.3646]: Checking for other bnetlauncher processes
[2017-10-07 23:02:51.3656]: No other bnetlauncher detected
[2017-10-07 23:02:51.3656]: Given parameter: -ow
[2017-10-07 23:02:51.3666]: Known key for game 'Overwatch'
[2017-10-07 23:02:51.5726]: battle.net client is fully running with pid = 9600
[2017-10-07 23:02:51.5736]: Issuing game launch command 'Pro' at '11:02:51.5736'
[2017-10-07 23:02:51.5896]: System.ComponentModel.Win32Exception (0x80004005): Unknown error (0x80041002)
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at bnetlauncher.Program.BnetStartProcess(String bnet_command)
[2017-10-07 23:02:55.5389]: Searching for new battle.net child processes for the game
[2017-10-07 23:02:55.6709]: No child process found.
[2017-10-07 23:02:56.2859]: No child process found.
[2017-10-07 23:02:56.9479]: No child process found.
[2017-10-07 23:02:57.5660]: No child process found.
[2017-10-07 23:02:58.2050]: No child process found.
[2017-10-07 23:02:58.8421]: No child process found.
[2017-10-07 23:02:59.4631]: No child process found.
[2017-10-07 23:03:00.1181]: No child process found.
[2017-10-07 23:03:00.7382]: No child process found.
[2017-10-07 23:03:01.3772]: No child process found.
[2017-10-07 23:03:02.0002]: No child process found.
[2017-10-07 23:03:02.6303]: No child process found.
[2017-10-07 23:03:03.2413]: No child process found.
[2017-10-07 23:03:03.8713]: No child process found.
[2017-10-07 23:03:04.5184]: No child process found.
[2017-10-07 23:03:05.1694]: No child process found.
[2017-10-07 23:03:05.8065]: No child process found.
[2017-10-07 23:03:06.4185]: No child process found.
[2017-10-07 23:03:06.9185]: No child process game found, giving up and exiting

**Comment by dafzor** [comment]
The battle.net client allows you to change the install location at will so there shouldn't be any reason to use symlinks. Could you try removing the symlink and see if that still gives you an error?

**Comment by robinhugy** [comment]
i just created symlink after bnetlauncher cant start my game, originally installed to h drive and is worked all time from battle.net

**Comment by dafzor** [comment]
Did it stop working with version 1.18? Could you check and see if 1.16 would still work on your system?
Also are you running battle.net client as administrator?

**Comment by TheLawsOfChaos** [comment]
Like dafzor said, the battlenet client allows you to move games quiet easily instead of using symlink (which causes all sorts of other problems in of itself). When you moved the location, did you go to the battlenet launcher, go to 'Already Installed? Locate the game.' and pick the folder? I myself have done it with multiple games (Overwatch, D3, WoW, and HotS) without issues.

**Comment by robinhugy** [comment]
i just use it for the first time

TheLawsOfChaos: i said i can start the game from battle.net

**Comment by TheLawsOfChaos** [comment]
I understand you can start it, I meant not using the symlink. You shouldn't
be required to use it, and it sounds like a possible one-off that needs to
be fixed.

**Comment by dafzor** [comment]
Trying to be a bit clearer here, the log file posted shows two errors:
* First is trying to obtain the path of the battle.net client, something that's new to 1.8. Thus me asking if it still happens in 1.6 so i'd know if it's an issue with the new code.
* Second is error actually launching the game command error indicating permission problems. Since symlinks are known to cause ocasional permission issues and are not necessary I asked to test without it to see if that changed anything.

I need a bit more info to try figure out what could be causing the problem.

**Comment by dafzor** [comment]
Closing for lack of response.

**Comment by robinhugy** [comment]
:|

**Comment by dafzor** [comment]
Do you even still have the problem with the latest version?

**Comment by robinhugy** [comment]
i didnt tried after that problem :|
i can check it in the next week

**Comment by robinhugy** [comment]
with the newest version it says
"Couldn't retrieve Battle.net Client install location
Please reinstall the Battle.net Client to fix the issue" :|

**Comment by dafzor** [comment]
Did reinstalling fix the issue?
