### ISSUE TITLE
bnetlauncher able to find battle.net launcher, won't start game.

### ISSUE THREAD

**Issue by black1298** [dafzor/bnetlauncher#17]
I assume this is a problem after the process has transferred to Blizzard's launcher but I don't know where else to ask.  Hopefully you can help me :)
~~~~~~~~~~~~~LOG~~~~~~~~~~~~~~~~~~

[2018-01-08 08:29:31.9957]: Battle.net Launcher for Steam version 1.18.6465.31319 started
[2018-01-08 08:29:32.0047]: Environment: Microsoft Windows NT 10.0.16299.0 (4.0.30319.42000), 64bit
[2018-01-08 08:29:32.0092]: Getting Machine details:
[2018-01-08 08:29:32.1288]: OS: Microsoft Windows 10 Home (10.0.16299, 64-bit, 1033)
[2018-01-08 08:29:32.1423]: CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz; RAM: 16384MB
[2018-01-08 08:29:32.1488]: GPU: Intel(R) HD Graphics 4600 (1024MB, 20.19.15.4835)
[2018-01-08 08:29:32.1533]: HDD: SSD2SC120G1CS1754D117-483, WDC WD10EZEX-00BN5A0
[2018-01-08 08:29:32.1603]: battlenet URI handler appears to present and correct
[2018-01-08 08:29:32.1703]: Checking for other bnetlauncher processes
[2018-01-08 08:29:32.1828]: No other bnetlauncher detected
[2018-01-08 08:29:32.1878]: Given parameter: ow
[2018-01-08 08:29:32.1918]: Known key for game 'Overwatch'
[2018-01-08 08:29:32.4491]: battle.net client is fully running with pid = 57048
[2018-01-08 08:29:32.4521]: Issuing game launch command 'Pro' at '08:29:32.4521'
[2018-01-08 08:29:32.4736]: System.ComponentModel.Win32Exception (0x80004005): Application not found
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at bnetlauncher.Program.BnetStartProcess(String bnet_command)
[2018-01-08 08:29:34.1241]: Searching for new battle.net child processes for the game
[2018-01-08 08:29:34.2943]: No child process found.
[2018-01-08 08:29:34.9474]: No child process found.
[2018-01-08 08:29:35.5896]: No child process found.

**Comment by dafzor** [comment]
Could you try using the Windows run dialogue (Windows key + R) and trying to launch `battlenet://Pro` and tell me if it works?

**Comment by black1298** [comment]
It returns with an application not found error

**Comment by dafzor** [comment]
Seems you battle.net client is not properly installed, reinstalling the battle.net client will hopefully fix your issues.

**Comment by black1298** [comment]
ugh I was afraid that was the issue... Thank you very much

**Comment by MoKiChU** [comment]
Hi,

First of all, thank you very much for your work.

However I wanted to talk to you about a problem that I suffered recently (and on the PC of my wife too). Since the last Battle.net update, when Battle.net is already running (minimized as a tray icon) and when you double-click on the shortcut created from Steam (Characteristic of the shortcut: Name: Overwatch / Target: "D:\My Games\Steam\BnetLauncher.exe" / Start In: "D:\My Games\Steam" / Launch Option: OW) the game does not run, the only way to unlock the process is to double click on the Battle.net tray icon, and the game is launched automatically (with Steam overlay).

Here is the log:

[2018-02-10 13:06:46.6149]: Battle.net Launcher for Steam version 1.18.6465.31319 started
[2018-02-10 13:06:46.6199]: Environment: Microsoft Windows NT 10.0.16299.0 (4.0.30319.42000), 64bit
[2018-02-10 13:06:46.6209]: Getting Machine details:
[2018-02-10 13:06:46.6780]: OS: Microsoft Windows 10 Professionnel (10.0.16299, 64 bits, 1036)
[2018-02-10 13:06:46.6780]: CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz; RAM: 16384MB
[2018-02-10 13:06:46.6790]: GPU: NVIDIA GeForce GTX 980 (4095MB, 23.21.13.9077)
[2018-02-10 13:06:46.6790]: HDD: Corsair Force GS, ST2000DX001-1CM164, Generic STORAGE DEVICE USB Device
[2018-02-10 13:06:46.6810]: battlenet URI handler appears to present and correct
[2018-02-10 13:06:46.6810]: Checking for other bnetlauncher processes
[2018-02-10 13:06:46.6840]: No other bnetlauncher detected
[2018-02-10 13:06:46.6850]: Given parameter: OW
[2018-02-10 13:06:46.6850]: Known key for game 'Overwatch'
[2018-02-10 13:08:46.7631]: not enough battle.net Helpers started.
[2018-02-10 13:08:46.7631]: Couldn't find the battle.net running and failed to start it. Exiting

The problem does not occur when Battle.net is not already running.

By launching the game via the command battlenet: // Pro, the game starts without problems (without Steam overlay of course)

Thank you in advance.


Note: If it can help you, on my PC the PID of:

- Battle.net.exe: 8652
- Battle.net Helper.exe: 1588
